services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: learntech-app
    container_name: learntech-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - learntech-network

  nginx:
    image: nginx:alpine
    container_name: learntech-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - learntech-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: learntech-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-learntech}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-learntech}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - learntech-network

networks:
  learntech-network:
    driver: bridge

volumes:
  dbdata:
